### ISSUE TITLE
Top part of the invoice editor app is a bit crowded on small a screen

### ISSUE THREAD

**Issue by johannesh2** [vaadin/ui-examples#16]
![image](https://user-images.githubusercontent.com/1398470/53988398-0a60e700-412c-11e9-8427-0c3463cff451.png)

**Comment by yuriy-fix** [comment]
@jouni, how should it be changed?
Should the buttons be positioned differently / add more indents?

**Comment by jouni** [comment]
Wrap the buttons in a container, so that they all wrap together on a new line.

Where’s the grid, btw?

**Comment by Peppe** [comment]
A little spacing wouldn't hurt either.
