### ISSUE TITLE
Update select column tabbing in invoice editor flow

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/ui-examples#33]
Bump the dependency of the `vaadin-grip-pro-flow` once the new release (`1.0.1`) is available. It will include the fix from the wc: https://github.com/vaadin/vaadin-grid-pro/commit/68c482409f8d6125b7e3052ba144af3591ec0f78.
Set `keepEditorOpen` on `GridPro`

**Comment by web-padawan** [comment]
The demo is now using a newer version where we changed to keep editor open by default, and opt out of it by using `singleCellEdit` property instead. So I assume this can be closed now.
